package com.fittrack.controller;
import com.fittrack.entity.*; import com.fittrack.repository.*; import com.fittrack.service.*;
import org.springframework.web.bind.annotation.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api") public class ApiController {
 private final DailyLogQueryRepository logs; private final MealItemRepository meals; private final WorkoutRepository workouts; private final WaterLogRepository water; private final CurrentUserService current; private final NutritionService nutrition;
 public ApiController(DailyLogQueryRepository l,MealItemRepository m,WorkoutRepository w,WaterLogRepository x,CurrentUserService c,NutritionService n){logs=l;meals=m;workouts=w;water=x;current=c;nutrition=n;}
 private Map<String,Object> ok(String m,Object d){return Map.of("success",true,"message",m,"data",d);}
 @GetMapping("/daily-logs") public Map<String,Object> logs(Authentication a){return ok("Daily logs",logs.findAllByUserIdOrderByDateAsc(current.get(a).id));}
 @PostMapping("/daily-logs") public Map<String,Object> save(Authentication a,@RequestBody DailyLog x){User u=current.get(a);var old=logs.findByUserIdAndDate(u.id,x.date);if(old.isPresent()){x.id=old.get().id;x.createdAt=old.get().createdAt;}x.user=u;calculateActivity(x,u);x.updatedAt=Instant.now();return ok("Daily log saved",logs.save(x));}
 private void calculateActivity(DailyLog x,User u){if(x.steps==null)x.steps=0L;if((x.distanceKm==null||x.distanceKm<=0)&&u.heightCm!=null){double strideM=u.heightCm*0.414/100.0;x.distanceKm=Math.round(x.steps*strideM/10.0)/100.0;}if((x.caloriesBurned==null||x.caloriesBurned<=0)&&x.distanceKm!=null){double weight=x.weight!=null?x.weight:(u.startingWeight==null?70:u.startingWeight);x.caloriesBurned=Math.round(weight*x.distanceKm*0.53*10.0)/10.0;}}
 @DeleteMapping("/daily-logs/{id}") public ResponseEntity<?> del(Authentication a,@PathVariable Long id){var x=logs.findByIdAndUserId(id,current.get(a).id);if(x.isEmpty())return ResponseEntity.notFound().build();logs.delete(x.get());return ResponseEntity.ok(ok("Deleted",Map.of()));}
 @GetMapping("/dashboard") public Map<String,Object> dashboard(Authentication a){User u=current.get(a);var all=logs.findAllByUserIdOrderByDateAsc(u.id);var latest=all.isEmpty()?null:all.get(all.size()-1);double start=u.startingWeight==null?84:u.startingWeight,goal=u.goalWeight==null?70:u.goalWeight,currentW=latest!=null&&latest.weight!=null?latest.weight:start;Map<String,Object>d=new LinkedHashMap<>();d.put("startingWeight",start);d.put("currentWeight",currentW);d.put("goalWeight",goal);d.put("lost",Math.round((start-currentW)*10.0)/10.0);d.put("remaining",Math.round((currentW-goal)*10.0)/10.0);d.put("today",latest==null?Map.of():latest);d.put("weightTrend",all.stream().filter(x->x.weight!=null).map(x->Map.of("date",x.date.toString(),"weight",x.weight)).toList());return ok("Dashboard",d);}
 @GetMapping("/weights") public Map<String,Object> weights(Authentication a){return ok("Weights",logs.findAllByUserIdOrderByDateAsc(current.get(a).id));}
 @GetMapping("/nutrition/search") public Map<String,Object> food(@RequestParam(defaultValue="") String q){return nutrition.search(q);}
 @GetMapping("/meals") public Map<String,Object> meals(Authentication a){return ok("Meals",meals.findAllByUserIdOrderByIdDesc(current.get(a).id));}
 @PostMapping("/meals") public ResponseEntity<?> meal(Authentication a,@RequestBody MealItem x){try{x.user=current.get(a);nutrition.populate(x);return ResponseEntity.ok(ok("Meal saved with automatic nutrition",meals.save(x)));}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body(Map.of("success",false,"message",e.getMessage()));}}
 @PutMapping("/meals/{id}") public ResponseEntity<?> updateMeal(Authentication a,@PathVariable Long id,@RequestBody MealItem incoming){var old=meals.findByIdAndUserId(id,current.get(a).id);if(old.isEmpty())return ResponseEntity.notFound().build();try{MealItem x=old.get();x.date=incoming.date;x.mealType=incoming.mealType;x.foodName=incoming.foodName;x.quantity=incoming.quantity;nutrition.populate(x);return ResponseEntity.ok(ok("Meal updated and nutrition recalculated",meals.save(x)));}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body(Map.of("success",false,"message",e.getMessage()));}}
 @DeleteMapping("/meals/{id}") public ResponseEntity<?> delMeal(Authentication a,@PathVariable Long id){var x=meals.findByIdAndUserId(id,current.get(a).id);if(x.isEmpty())return ResponseEntity.notFound().build();meals.delete(x.get());return ResponseEntity.ok(ok("Meal deleted",Map.of()));}
 @GetMapping("/workouts") public Map<String,Object> workouts(Authentication a){return ok("Workouts",workouts.findAllByUserIdOrderByIdDesc(current.get(a).id));}
 @PostMapping("/workouts") public Map<String,Object> workout(Authentication a,@RequestBody Workout x){x.user=current.get(a);return ok("Workout saved",workouts.save(x));}
 @DeleteMapping("/workouts/{id}") public ResponseEntity<?> delWorkout(Authentication a,@PathVariable Long id){var x=workouts.findByIdAndUserId(id,current.get(a).id);if(x.isEmpty())return ResponseEntity.notFound().build();workouts.delete(x.get());return ResponseEntity.ok(ok("Workout deleted",Map.of()));}
 @GetMapping("/water") public Map<String,Object> waterLogs(Authentication a){return ok("Water logs",water.findAllByUserIdOrderByIdDesc(current.get(a).id));}
 @PostMapping("/water") public Map<String,Object> water(Authentication a,@RequestBody WaterLog x){x.user=current.get(a);return ok("Water added",water.save(x));}
 @DeleteMapping("/water/{id}") public ResponseEntity<?> delWater(Authentication a,@PathVariable Long id){var x=water.findByIdAndUserId(id,current.get(a).id);if(x.isEmpty())return ResponseEntity.notFound().build();water.delete(x.get());return ResponseEntity.ok(ok("Water deleted",Map.of()));}
 @GetMapping("/wellness") public Map<String,Object> wellness(Authentication a){User u=current.get(a);var all=logs.findAllByUserIdOrderByDateAsc(u.id);DailyLog latest=all.isEmpty()?null:all.get(all.size()-1);double weight=latest!=null&&latest.weight!=null?latest.weight:(u.startingWeight==null?0:u.startingWeight),height=u.heightCm==null?0:u.heightCm;Double bmi=(weight>0&&height>0)?weight/Math.pow(height/100.0,2):null;String cat="Add height and weight";if(bmi!=null){if(bmi<18.5)cat="Underweight";else if(bmi<25)cat="Healthy range";else if(bmi<30)cat="Overweight range";else cat="Obesity range";}double min=height>0?18.5*Math.pow(height/100.0,2):0,max=height>0?24.9*Math.pow(height/100.0,2):0;int waterGoal=weight>0?(int)Math.round(weight*35):2500;return ok("Wellness",Map.of("weight",weight,"heightCm",height,"bmi",bmi==null?0:Math.round(bmi*10.0)/10.0,"bmiCategory",cat,"healthyWeightMin",Math.round(min*10.0)/10.0,"healthyWeightMax",Math.round(max*10.0)/10.0,"suggestedWaterMl",waterGoal));}
}
