CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    starting_weight DOUBLE PRECISION,
    goal_weight DOUBLE PRECISION,
    height_cm DOUBLE PRECISION,
    age INTEGER,
    sex VARCHAR(255),
    daily_step_goal INTEGER,
    daily_water_goal DOUBLE PRECISION,
    sync_token_hash VARCHAR(255),
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE daily_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    log_date DATE NOT NULL,
    weight DOUBLE PRECISION,
    steps BIGINT,
    distance_km DOUBLE PRECISION,
    calories_burned DOUBLE PRECISION,
    water_liters DOUBLE PRECISION,
    sleep_hours DOUBLE PRECISION,
    sugar_free BOOLEAN,
    workout_completed BOOLEAN,
    workout_duration INTEGER,
    workout_type VARCHAR(255),
    mood VARCHAR(255),
    energy_level INTEGER,
    notes VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_daily_logs_user
        FOREIGN KEY (user_id) REFERENCES app_users(id),

    CONSTRAINT uk_daily_logs_user_date
        UNIQUE (user_id, log_date)
);

CREATE TABLE meal_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date DATE,
    meal_type VARCHAR(255),
    food_name VARCHAR(255),
    quantity DOUBLE PRECISION,
    unit VARCHAR(255),
    calories DOUBLE PRECISION,
    protein DOUBLE PRECISION,
    carbohydrates DOUBLE PRECISION,
    fat DOUBLE PRECISION,
    fiber DOUBLE PRECISION,
    sugar DOUBLE PRECISION,
    sodium_mg DOUBLE PRECISION,
    health_rating VARCHAR(255),
    health_reason VARCHAR(1000),
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_meal_item_user
        FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE TABLE workout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    workout_date DATE,
    workout_type VARCHAR(255),
    exercise_name VARCHAR(255),
    sets INTEGER,
    repetitions INTEGER,
    duration INTEGER,
    calories_burned DOUBLE PRECISION,
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_workout_user
        FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE TABLE water_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date DATE,
    amount_ml INTEGER,
    logged_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_water_log_user
        FOREIGN KEY (user_id) REFERENCES app_users(id)
);